/*
 * Project name:
     Controller.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     26.04.2018
 * Time of creation
     22:34:25
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Mikromedia_Plus_for_STM32_ARM
                      http://www.mikroe.com/mikromedia/plus/stm32-m4/
     Oscillator:      150000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Controller_objects.h"
#include <stdbool.h>
#include "systick.h"
#include <stdint.h>
#include "built_in.h"


uint32_t old_time_count;
bool Send_data,sendMessage;
//------------------------------------------------------------------------------
volatile bool uartRX_flag;
//bit update_time;
//volatile uint8_t rx_buffer[BUFFER_SIZE];
int er;
bool pushButton;
volatile unsigned int rx_wr_index=0;
volatile bool end_packet=false;
volatile  unsigned char sizeOfBuffer=0;
volatile uint32_t rx_time = 0;
volatile uint32_t rx_time_previos = 0;
extern  int system_reg[600];
extern volatile uint8_t frame[BUFFER_SIZE];
extern unsigned char transmission_ready_Flag;
void (*send_data_again)() = 0;
volatile char myBuf[15];
bool dataEEprom=false;
bool msgOk=false;
//extern float press;
//------------------------------------------------------------------------------
//Timer2 Prescaler :0; Preload = 119; Actual Interrupt Time = 1 us

//Place/Copy this part in declaration section
/*void RTC_ISR()iv IVT_INT_RTC_Alarm ics ICS_AUTO
{
    if(get_RTC_second_flag_state() == true)
    {
        update_time = 1;
        clear_RTC_second_flag();
    }

    clear_RTC_overflow_flag();
    while(get_RTC_operation_state() == false);
}*/
void InitTimer2(){
  RCC_APB1ENR.TIM2EN = 1;
  TIM2_CR1.CEN = 0;
  TIM2_PSC = 0;
  TIM2_ARR = 119;
  NVIC_IntEnable(IVT_INT_TIM2);
  TIM2_DIER.UIE = 1;
  //TIM2_CR1.CEN = 1;
}

void Timer2_interrupt() iv IVT_INT_TIM2 {
  TIM2_SR.UIF = 0;
  rx_time++;
  if(rx_time-rx_time_previos>3645 ){
       //USART2_CR1bits.RXNEIE = 0;
       sizeOfBuffer=rx_wr_index;
       uartRX_flag=false;
       end_packet=true;
       rx_time=0;
       rx_time_previos=0;
       rx_wr_index=0;
       TIM2_CR1.CEN = 0;
       /*IntToStr(frame[9], myBuf);Ltrim(myBuf);
       UART2_Write_Text("buffer_9 = ");
       UART2_Write_Text(myBuf);
       UART2_Write_Text("\n");
        IntToStr(frame[10], myBuf);Ltrim(myBuf);
       UART2_Write_Text("buffer_10 = ");
       UART2_Write_Text(myBuf);
       UART2_Write_Text("\n");*/

       }
  //Enter your code here
}

//------------------------------------------------------------------------------
void USART_init(){
    UART2_Init_Advanced(9600 , _UART_8_BIT_DATA, _UART_NOPARITY, _UART_ONE_STOPBIT, &_GPIO_MODULE_USART2_PA23);
    USART2_BRR = 0xC35;                               //Set value for required baud rate
    USART2_CR1bits.RXNEIE = 1;       // enable uart rx interrupt
    USART2_CR1bits.TXEIE = 0;
    USART2_CR1bits.UE = 1;
    NVIC_IntEnable(IVT_INT_USART2);  // enable interrupt vector
    USART2_CR1bits.TE=1;
    USART2_CR1bits.RE=1;
}

void USARTINTERRUPT() iv IVT_INT_USART2 ics ICS_AUTO{

     if(USART2_SRbits.RXNE != 0){
           if(TIM2_CR1.CEN == 0)TIM2_CR1.CEN = 1;
           rx_time_previos = rx_time;
           uartRX_flag=true;
           frame[rx_wr_index]=(uint8_t)(UART2_Read() & 0xFF);
           rx_wr_index++;
           if (rx_wr_index == BUFFER_SIZE) rx_wr_index=0;

     }
   }
    RTC_TimeTypeDef      My_Time;
    RTC_TimeTypeDef      Read_Time;
    RTC_DateTypeDef      My_Date;
    RTC_DateTypeDef      Read_Date;
//------------------------------------------------------------------------------
void main() {

  InitSysTick();
  USART_init();
  InitTimer2();

   /*// Mon 31/12/2015
    My_Date.RTC_DayofWeek     = 5;
    My_Date.RTC_Date_Tens     = 3;
    My_Date.RTC_Date_Units    = 1;
    My_Date.RTC_Month_Tens    = 1;
    My_Date.RTC_Month_Units   = 2;
    My_Date.RTC_Year_Tens     = 1;
    My_Date.RTC_Year_Units    = 5;


    //09:59:30pm
    My_Time.RTC_Hour_Tens     = 0;
    My_Time.RTC_Hour_Units    = 9;
    My_Time.RTC_Min_Tens      = 5;
    My_Time.RTC_Min_Units     = 9;
    My_Time.RTC_Sec_Tens      = 3;
    My_Time.RTC_Sec_Units     = 0;
    My_Time.RTC_H12           = 1;
    if (RTC_Init(255, 127, 1))
         Message("RTC Initialise SUCCESS...");
    else
         Message("RTC Initialise FAILED...");
    Delay_ms(2000);

    // Set the Time.
    if (RTC_SetTime(&My_Time, -37))
         Message("Time Set SUCCESS...");
    else
         Message("Time Set FAILED...");
    Delay_ms(2000);

    // Set the Date.
    RTC_SetDate(&My_Date);*/
   //ptr= send_data_packet;
  //rec=reciev_data_packet;
  modbus_configure(1000,200,10);
  Start_TP();
  EnableInterrupts();
  DrawRoundBox (&Messages_Box);
  Messages_Label.Caption = "UPDATE_DIS";
  DrawLabel (&Messages_Label);
/*while(end_packet==false){
  reciev_data_packet(COMP_DEL,46);
  Delay_ms(1000);

  }*/
 //end_packet=false;
 //data_eeprom();startPage();
 /*end_packet=false;
  checkResponse();
  check_packet_status();*/

  DrawRoundBox (&Messages_Box);
  Messages_Label.Caption = "DIS_UPDATE";
  DrawLabel (&Messages_Label);
  DisableInterrupts();
  countPacket=1;
  //ptr= send_data_packet;
  //rec=reciev_data_packet;
  while (1) {

   if(end_packet )
   {
     end_packet=false;
     checkResponse();
     if(!dataEEprom && msgOk){dataEEprom=true;data_eeprom();startPage();msgOk=false;}//UART2_Write_Text("finisheeprom");
     if(msgOk){countPacket++;  msgOk=false;}// UART2_Write_Text("privet");
     //USART2_CR1bits.RXNEIE = 1;
     //UART2_Write_Text("privet");
   }
  //if(!msgOk){reciev_data_packet(adressRegReciev,nomRegReciev);Delay_ms(3000);}

    /* check_packet_status();
     if(system_reg[ERRORS_1]!=er){
                                er=system_reg[ERRORS_1];
                                if(er>0){
                                  Messages_Label.Font_Color= 0xF800;
                                  DrawRoundBox (&Messages_Box);
                                  Messages_Label.Caption = "FIND_ERROR";
                                  DrawLabel (&Messages_Label);
                                  find_errors();}
                                else {
                                  Messages_Label.Font_Color= 0x07E0;
                                  DrawRoundBox (&Messages_Box);
                                  Messages_Label.Caption = "SYSTEM_OK";
                                  DrawLabel (&Messages_Label);

                                }
                                }


   }*/
   DisableInterrupts();
   if(millis() - old_time_count > 3000 )//
       {     
           old_time_count = millis();

           if(dataEEprom && !pushButton)selectPage();
           else if(!dataEEprom && !pushButton) reciev_data_packet(COMP_DEL,46);
           if(pushButton) {send_data_packet(adressRegSend,nomRegSend);}
        }

    Check_TP();
  EnableInterrupts();

    }

}