/*
 * Project name:
     Controller.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     26.04.2018
 * Time of creation
     22:34:25
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Mikromedia_Plus_for_STM32_ARM
                      http://www.mikroe.com/mikromedia/plus/stm32-m4/
     Oscillator:      150000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Controller_objects.h"
#include <stdbool.h>
#include "systick.h"
#include <stdint.h>
#include "built_in.h"


uint32_t old_time_count;
bool Send_data,sendMessage;
//------------------------------------------------------------------------------
volatile bool uartRX_flag;
//bit update_time;
//volatile uint8_t rx_buffer[BUFFER_SIZE];
int er_1,er_2;
bool pushButton;
volatile unsigned int rx_wr_index=0;
volatile bool end_packet=false;
volatile  unsigned char sizeOfBuffer=0;
volatile uint32_t rx_time = 0;
volatile uint32_t rx_time_previos = 0;
extern  int system_reg[600];
extern volatile uint8_t frame[BUFFER_SIZE];
extern unsigned char transmission_ready_Flag;
void (*send_data_again)() = 0;
volatile char myBuf[15];
bool dataEEprom=false;
bool msgOk=false;
//extern TTime MyTime;
RTC_TimeTypeDef _time;
RTC_DateTypeDef _date;
extern TScreen*  CurrentScreen;
//extern float press;
//------------------------------------------------------------------------------
//Timer2 Prescaler :0; Preload = 119; Actual Interrupt Time = 1 us

//Place/Copy this part in declaration section
/*
void RTC_ISR()iv IVT_INT_RTC_Alarm ics ICS_AUTO
{
    if(get_RTC_second_flag_state() == true)
    {
        update_time = 1;
        clear_RTC_second_flag();
    }

    clear_RTC_overflow_flag();
    while(get_RTC_operation_state() == false);
}    */
void InitTimer2(){
  RCC_APB1ENR.TIM2EN = 1;
  TIM2_CR1.CEN = 0;
  TIM2_PSC = 0;
  TIM2_ARR = 119;
  NVIC_IntEnable(IVT_INT_TIM2);
  TIM2_DIER.UIE = 1;
  //TIM2_CR1.CEN = 1;
}

void Timer2_interrupt() iv IVT_INT_TIM2 {
  TIM2_SR.UIF = 0;
  rx_time++;
  if(rx_time-rx_time_previos>3645 ){
       //USART2_CR1bits.RXNEIE = 0;
       sizeOfBuffer=rx_wr_index;
       uartRX_flag=false;
       end_packet=true;
       rx_time=0;
       rx_time_previos=0;
       rx_wr_index=0;
       TIM2_CR1.CEN = 0;
       checkResponse();

       }
  //Enter your code here
}

//------------------------------------------------------------------------------
void USART_init(){
    UART2_Init_Advanced(9600 , _UART_8_BIT_DATA, _UART_NOPARITY, _UART_ONE_STOPBIT, &_GPIO_MODULE_USART2_PA23);
    //USART2_BRR = 0xC35;                               //Set value for required baud rate
    USART2_CR1bits.RXNEIE = 1;       // enable uart rx interrupt
    USART2_CR1bits.TXEIE = 0;
    USART2_CR1bits.UE = 1;
    USART2_CR1bits.TE=1;
    USART2_CR1bits.RE=1;
    NVIC_IntEnable(IVT_INT_USART2);  // enable interrupt vector
}

void USARTINTERRUPT() iv IVT_INT_USART2 ics ICS_AUTO{

     if(USART2_SRbits.RXNE != 0){
           if(TIM2_CR1.CEN == 0)TIM2_CR1.CEN = 1;
           rx_time_previos = rx_time;
           uartRX_flag=true;
           frame[rx_wr_index]=(uint8_t)(UART2_Read() & 0xFF);
           rx_wr_index++;
           if (rx_wr_index == BUFFER_SIZE) rx_wr_index=0;

     }
   }
  //---------------------------------------------------------------------------
void printTime(RTC_TimeTypeDef *RTC_TimeStruct,RTC_DateTypeDef *RTC_DateStruct)
 {    // RTC_TimeTypeDef *RTC_TimeStruct,RTC_DateTypeDef *RTC_DateStruct
      char txt[4];
      char *res;
      unsigned char mon;
      mon = RTC_DateStruct->RTC_Month_Tens*10 +  RTC_DateStruct->RTC_Month_Units;
      ByteToStr(RTC_TimeStruct->RTC_Hour_Tens,txt);
      res = Ltrim(txt);
      strcpy(DateTime.Caption,res);
      ByteToStr(RTC_TimeStruct->RTC_Hour_Units,txt);
      res = Ltrim(txt);
      strcat(DateTime.Caption,res);
      strcat(DateTime.Caption,":");
      ByteToStr(RTC_TimeStruct->RTC_Min_Tens,txt);
      res = Ltrim(txt);
      strcat(DateTime.Caption,res);
      ByteToStr(RTC_TimeStruct->RTC_Min_Units ,txt);
      res = Ltrim(txt);
      strcat(DateTime.Caption,res);
      strcat(DateTime.Caption,"/");
      ByteToStr(RTC_DateStruct->RTC_Date_Tens,txt);
      res = Ltrim(txt);
      strcat(DateTime.Caption,res);
      ByteToStr(RTC_DateStruct->RTC_Date_Units,txt);
      res = Ltrim(txt);
      strcat(DateTime.Caption,res);

      switch (mon)  //
      {
           case 1 :   strcat(DateTime.Caption,"JAN");break;
           case 2 :   strcat(DateTime.Caption,"FAB");break;
           case 3 :   strcat(DateTime.Caption,"MAR");break;
           case 4 :   strcat(DateTime.Caption,"APR");break;
           case 5 :   strcat(DateTime.Caption,"MAY");break;
           case 6 :   strcat(DateTime.Caption,"JUN");break;
           case 7 :   strcat(DateTime.Caption,"JUL");break;
           case 8 :   strcat(DateTime.Caption,"AUG");break;
           case 9 :   strcat(DateTime.Caption,"SEP");break;
           case 10 :  strcat(DateTime.Caption,"OCT");break;
           case 11 :  strcat(DateTime.Caption,"NOV");break;
           case 12 :  strcat(DateTime.Caption,"DEC");break;
      }

 }
//------------------------------------------------------------------------------
void main() {

    //RTC_TimeTypeDef      Read_Time;
    //RTC_DateTypeDef      Read_Date;
    RTC_Init();
    //RTC_Init(255, 127, 1);
/*Delay_ms(2000);
     if (RTC_SetTime(&My_Time, -37))
          My_Time.RTC_Hour_Units    = 1;
    else
          My_Time.RTC_Hour_Units    = 0;
    Delay_ms(2000);
     // Set the Date.
    RTC_SetDate(&My_Date);*/
  //---------------
  InitSysTick();
  USART_init();
  InitTimer2();
  modbus_configure(1000,200,10);
  Start_TP();
  EnableInterrupts();
  /*
  DrawRoundBox (&Messages_Box);
  Messages_Label.Caption = "UPDATE_DIS";
  DrawLabel (&Messages_Label);


  DrawRoundBox (&Messages_Box);
  Messages_Label.Caption = "DIS_UPDATE";
  DrawLabel (&Messages_Label);
  */
  DisableInterrupts();
  countPacket=1;

  while (1) {
    if(!dataEEprom && msgOk){dataEEprom=true;data_eeprom();startPage();msgOk=false;}//UART2_Write_Text("finisheeprom");
    if(msgOk){countPacket++;  msgOk=false;}//

    if(system_reg[ERRORS_1]!=er_1 ||system_reg[ERRORS_2]!=er_2 ){

                                 if(system_reg[ERRORS_1]!=er_1)er_1=system_reg[ERRORS_1];
                                 else  er_2=system_reg[ERRORS_2];
                                if(er_1>0 || er_2>0 ){
                                  DateTime.Font_Color= 0xF800;
                                  //DrawRoundBox (&Messages_Box);
                                  //DateTime.Caption = "ERROR";
                                  DrawLabel (&DateTime);
                                  find_errors();}
                                else if(er_1==0 && er_2==0) {
                                  DateTime.Font_Color= 0x07E0;
                                  //DrawRoundBox (&Messages_Box);
                                  //DateTime.Caption = "_OK";
                                  DrawLabel (&DateTime);

                                }
                                }

   //}
   DisableInterrupts();
   if(millis() - old_time_count >1100 )//
       {    

            static unsigned char n=0;
            static unsigned char f=0;
            n++;
            if(n>60)
            {
                n=0;
                RTC_GetDate(&_date);
                //RTC_PrintDate(&Read_Date);

                RTC_GetTime(&_time);
               // RTC_PrintTime(&Read_Time);
                printTime(&_time,&_date);
                if (CurrentScreen==&HOME)
                {
                DrawRoundBox (&Messages_Box);DrawLabel (&DateTime);
                }
            }


           old_time_count = millis();
           
          if(dataEEprom && !pushButton){selectPage();f=0; }
          else if(!dataEEprom && !pushButton) reciev_data_packet(COMP_DEL,48);
          if(pushButton) 
          {
          send_data_packet(adressReg,nomReg);f++;
           if(f>5){DateTime.Caption = "LOST";DrawLabel (&DateTime);pushButton=false;f=0;}
          }
        }


    Check_TP();
    
  EnableInterrupts();



}
}